language: perl
perl:
  - "5.18"
  - "5.16"
before_install:
  - cpanm ExtUtils::MakeMaker::CPANfile
  - cpanm -n git://github.com/kan/coveralls-perl.git
script: perl Makefile.PL && cover -test
after_success:
  - cover -report coveralls
notifications:
  email:
    - i.naoya+md2inao@gmail.com
  irc:
    - "irc.freenode.net#md2inao"
